name: ✍️ New Blog Post
description: Write a post; a bot will publish it to _posts/
title: "[Post]: "
labels: ["blog:post"]
body:
  - type: input
    id: post_title
    attributes: { label: Title }
    validations: { required: true }
  - type: input
    id: slug
    attributes: { label: Slug (lowercase-hyphens), placeholder: my-first-post }
    validations: { required: true }
  - type: input
    id: publish_date
    attributes: { label: Publish date (YYYY-MM-DD), placeholder: 2025-09-20 }
    validations: { required: true }
  - type: input
    id: tags
    attributes: { label: Tags (comma-separated), placeholder: dev, notes, life }
  - type: textarea
    id: summary
    attributes: { label: One-paragraph summary }
  - type: textarea
    id: body
    attributes:
      label: Post body (Markdown)
      placeholder: "## Intro\nWrite in **Markdown**. Drag–drop images here; GitHub will auto-host them."
    validations: { required: true }
