name: Create Post from Issue

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    if: startsWith(github.event.issue.title, '[POST]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Post File
        run: |
          # --- FILE SETUP ---
          POST_TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/\[POST\] //')
          POST_CONTENT="${{ github.event.issue.body }}"
          FILENAME_SLUG=$(echo "$POST_TITLE" | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g' -e 's/--*/-/g' -e 's/[^a-z0-9-]//g')
          POST_FILENAME="Mywebsite/posts/$FILENAME_SLUG.md"

          # --- CREATE MARKDOWN FILE ---
          echo "---" > "$POST_FILENAME"
          echo "title: \"$POST_TITLE\"" >> "$POST_FILENAME"
          echo "date: $(date +'%Y-%m-%d')" >> "$POST_FILENAME"
          # Add other front matter if needed, e.g., author, tags
          echo "---" >> "$POST_FILENAME"
          echo "" >> "$POST_FILENAME"
          echo "$POST_CONTENT" >> "$POST_FILENAME"
          
          echo "Created post file at $POST_FILENAME"

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "BOT: New post from issue #${{ github.event.issue.number }}"
          file_pattern: 'Mywebsite/posts/*.md'
          repository: .
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
